# Site settings
title: "K3s Homelab by FRUCHTiii"
description: "Documentation how I setup my homlab using K3s"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"

aux_links:
  "View on GitHub":
    - "https://github.com/FRUCHTiii/homelab_k3s_argocd"