# Site settings
title: K3s Homelab by FRUCHTiii
description: Documentation how I setup my homlab using K3s
baseurl: "/homelab_k3s"
url: https://fruchtiii.github.io

#Theme
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

aux_links:
  "View on GitHub":
    - "//github.com/FRUCHTiii/homelab_k3s"

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md"]

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-P622X0WMMQ
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

# Collections
collections:
  k3s:
    output: true

collections_dir: docs

defaults:
  - scope:
      path: ""
      type: "k3s"
    values:
      layout: "default"

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    k3s: 
      name: k3s
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false